apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-multimode
spec:
  params:
    - name: github-url 
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: github-url 
          value: $(params.github-url)
      workspaces:
        - name: shared-data
          workspace: shared-data
    - name: build-task
      runAfter:
        - git-clone
      taskRef:
        name: build-task
      workspaces:
        - name: shared-data
          workspace: shared-data


